[mypy]
python_version = 3.8
files = app/core, app/utils, app/dto

# Stricter, but compatible with incremental rollout
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
check_untyped_defs = True

# External packages without type hints
ignore_missing_imports = True

