name: Update VERSION file

on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read current version
        id: read_version
        run: |
          version=$(cat VERSION)
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Analyze commits and determine bump
        id: analyze_commits
        run: |
          commits=$(git log -1 --pretty=format:%B)
          echo "Last commit message(s): $commits"

          bump="patch" # default

          if echo "$commits" | grep -iq "BREAKING CHANGE"; then
            bump="major"
          elif echo "$commits" | grep -iq "feat"; then
            bump="minor"
          elif echo "$commits" | grep -iq "fix"; then
            bump="patch"
          fi

          echo "Version bump type: $bump"
          echo "bump=$bump" >> $GITHUB_ENV

      - name: Calculate new version
        id: calc_version
        run: |
          IFS='.' read -r major minor patch <<< "$version"

          if [ "$bump" = "major" ]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [ "$bump" = "minor" ]; then
            minor=$((minor + 1))
            patch=0
          else
            patch=$((patch + 1))
          fi

          new_version="$major.$minor.$patch"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Update VERSION file
        run: |
          echo $new_version > VERSION

      - name: Commit VERSION file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "chore: update VERSION to $new_version" || echo "No changes to commit"
          git push
